version: "3.1"

networks:
  app-tier:
    driver: bridge
services:
  mysql:
    networks:
      - app-tier
    image: mysql
    container_name: mysql_container
    restart: always
    ports:
      - "3300:3300"
    environment:
      - MYSQL_ROOT_PASSWORD=qawsedrf1!
      - MYSQL_PASSWORD=qawsedrf1!
      - MYSQL_DATABASE=donorticon
  app:
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    restart: always
    ports:
      - "4000:4000"
    links:
      - mysql
    depends_on:
      - mysql